gripper_action_controller:
  # Feedback rate in Hz
  publish_rate: 100
  min_gap_counts: 224
  counts_to_meters: 0.8
  # Gripper width in meters [0, 0.140]
  min_gap:    0.0
  max_gap:    0.085
  # Gripper speed in m/s [0.03, 0.25]
  min_speed:  0.03
  max_speed:  0.25
  # Gripper force in N. [10, 125]
  min_force:  10.0
  max_force:  250.0
  # Joint name
  joint_name: finger_joint
